services:
  postgres:
    image: postgres:15.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.docker-data/postgres-db:/var/lib/postgresql/data
      - ./init-extensions-db.sh:/docker-entrypoint-initdb.d/init-extensions-db.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local-db

  cache:
    image: redis/redis-stack:7.2.0-v2
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./.docker-data/redis-db:/data
volumes:
  cache:
    driver: local
