name: Build and deploy apps

permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        options:
          - dev
          - stage
          - prod
        description: "Environment to apply changes to"
        default: "dev"

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}


jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.define-envs.outputs.environment }}
      release-tag: ${{ steps.define-envs.outputs.release-tag }}
      image-tag: ${{ steps.define-envs.outputs.image-tag }}
      docker-url: ${{ steps.define-envs.outputs.docker-url }}
      is-dev: ${{ steps.define-envs.outputs.is-dev }}
      is-release: ${{ steps.define-envs.outputs.is-release }}

    steps:
      - name: Base env info
        run: |
          echo BRANCH_SLUG="$(echo '${{ env.BRANCH_NAME }}' | sed 's/[^a-zA-Z0-9]/-/g')" >> $GITHUB_ENV
          echo ENVIRONMENT=${{ inputs.environment || 'dev' }} >> $GITHUB_ENV

      - name: Define envs information
        id: define-envs
        run: |
          echo ${{ env.ENVIRONMENT }}
          echo ${{ env.BRANCH_SLUG }}

          echo image-tag=${{ startsWith(env.BRANCH_NAME, 'release/') && env.BRANCH_SLUG || format('{0}-{1}', github.run_id, github.run_attempt) }} >> $GITHUB_OUTPUT
          echo environment=${{ env.ENVIRONMENT }} >> $GITHUB_OUTPUT
          echo is-dev=${{ env.ENVIRONMENT == 'dev' && 'true' || '' }} >> $GITHUB_OUTPUT
          echo is-release=${{ startsWith(env.BRANCH_NAME, 'release/') && 'true' || '' }} >> $GITHUB_OUTPUT
          echo release-tag=${{ format('{0}-{1}', env.ENVIRONMENT, 'last-release') }} >> $GITHUB_OUTPUT
          echo docker-url=${{ format('{0}.dkr.ecr.{1}.amazonaws.com', vars.DEPLOYMENT_AWS_ACCOUNT_ID, vars.DEPLOYMENT_AWS_ACCOUNT_REGION) }} >> $GITHUB_OUTPUT

  build-apps:
    needs: [ prepare ]
    runs-on: ubuntu-latest
    outputs:
      affected-projects: ${{ steps.get-affected-projects.outputs.affected-projects }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0

      - name: Verify if last release tag exists, and define nx command to use
        id: nx
        run: |
          if [ $(git tag -l ${{ needs.prepare.outputs.release-tag }}) ]; then
           echo "Last release tag exists, will process with affected applications"
           echo exec-cmd="npx nx affected --base=${{ needs.prepare.outputs.release-tag }}" >> $GITHUB_OUTPUT
           echo show-apps="npx nx show projects --json --type app --affected --base ${{ needs.prepare.outputs.release-tag }}" >> $GITHUB_OUTPUT
          else
           echo "No last release tag exists, all apps will be deployed"
           echo exec-cmd="npx nx run-many" >> $GITHUB_OUTPUT
           echo show-apps="npx nx show projects --json --type app" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install environment
        run: yarn install

      - name: Build apps and libraries
        run: ${{ steps.nx.outputs.exec-cmd }} -t build

#      readme needed because of limitation of upload artifact action
#      https://github.com/actions/upload-artifact/issues/174
      - name: Upload builds
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            dist
            README.md
          if-no-files-found: error

      - name: Get affected projects
        id: get-affected-projects
        run: echo affected-projects=$(${{ steps.nx.outputs.show-apps }} --with-target build) >> $GITHUB_OUTPUT

  apply-tf-ci-changes:
    needs: [ prepare, build-apps ]
    strategy:
      matrix:
        project: ${{ fromJson(needs.build-apps.outputs.affected-projects) }}
# ci changes are applied only for dev environment, essentially it's global changes for the deployment account
    if: ${{ needs.prepare.outputs.is-dev }}
    uses: softkitit/github-actions-terraform/.github/workflows/cd-apply-terraform-changes.yml@main
    with:
      environment: "deployment"
      terraform-folder: apps/${{ matrix.project }}/terraform-ci
    secrets: inherit

  apply-tf-app-changes:
    needs: [ prepare, build-apps ]
    strategy:
      matrix:
        project: ${{ fromJson(needs.build-apps.outputs.affected-projects) }}
    uses: softkitit/github-actions-terraform/.github/workflows/cd-apply-terraform-changes.yml@main
    with:
      environment: ${{ needs.prepare.outputs.environment }}
      terraform-folder: apps/${{ matrix.project }}/terraform
    secrets: inherit

  build-and-push-images:
    needs: [ prepare, build-apps, apply-tf-ci-changes ]
    strategy:
      matrix:
        project: ${{ fromJson(needs.build-apps.outputs.affected-projects) }}
    uses: softkitit/github-actions-terraform/.github/workflows/ci-build-and-push-docker-image.yml@main
    with:
      environment: ${{ needs.prepare.outputs.environment }}
      ecr-repository-name: ${{ github.event.repository.name }}-${{ matrix.project }}
      image-tag: ${{ needs.prepare.outputs.image-tag }}
      docker-file-path: apps/${{ matrix.project }}/Dockerfile
      additional-artifact: build
      deployment-account-id: ${{ vars.DEPLOYMENT_AWS_ACCOUNT_ID }}
    secrets: inherit

  deploy-app:
    needs: [ prepare, build-and-push-images ]
    strategy:
      matrix:
        project: ${{ fromJson(needs.build-apps.outputs.affected-projects) }}
    uses: softkitit/github-actions-terraform/.github/workflows/cd-deploy-to-ecs.yml@main
    with:
      environment: ${{ needs.prepare.outputs.environment }}
      ecs-cluster-name: ${{ format('{0}-{1}', github.event.repository.owner.login, needs.prepare.outputs.environment) }}
      ecs-service-name: ${{ format('{0}-{1}-{2}-{3}', github.event.repository.owner.login, needs.prepare.outputs.environment, github.event.repository.name, matrix.project) }}
      ecr-repository-name: ${{ format('{0}-{1}', github.event.repository.name, matrix.project) }}
      ecr-repository-account-id: ${{ vars.DEPLOYMENT_AWS_ACCOUNT_ID }}
      container-name: ${{ format('{0}-{1}', github.event.repository.name, matrix.project) }}
      image-tag: ${{ needs.prepare.outputs.image-tag }}
      image: ${{ format('{0}/{1}-{2}:{3}', needs.prepare.outputs.docker-url, github.event.repository.name, matrix.project, needs.prepare.outputs.image-tag) }}
    secrets: inherit






