name: PR on main

permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  pull_request:
    branches:
      - main
    types: [ opened, reopened, synchronize ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.define-envs.outputs.environments }}
      release-tag: ${{ steps.define-envs.outputs.release-tag }}
      is-release: ${{ steps.define-envs.outputs.is-release }}

    steps:
      - name: Define envs information
        id: define-envs
        run: |
            echo is-release=${{ startsWith(github.head_ref, 'release/') && 'true' || '' }} >> $GITHUB_OUTPUT
            echo environments='${{ startsWith(github.head_ref, 'release/') && vars.RELEASE_ENVIRONMENTS || vars.DEV_ENVIRONMENTS }}' >> $GITHUB_OUTPUT
            echo release-tag=${{ startsWith(github.head_ref, 'release/') && 'last-release' || 'main' }} >> $GITHUB_OUTPUT

  lint-and-run-tests:
    needs: [ prepare ]
    runs-on: ubuntu-latest
    outputs:
        affected-projects: ${{ steps.get-affected-projects.outputs.affected-projects }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Verify if last release tag exists, and define nx command to use
        id: nx
        run: |
          if [ $(git tag -l ${{ needs.prepare.outputs.release-tag }}) ] || [[ 'main' == '${{ needs.prepare.outputs.release-tag }}' ]]; then
           echo "Last release tag exists, will process with affected applications"
           echo exec-cmd="nx affected --base=${{ needs.prepare.outputs.release-tag }}" >> $GITHUB_OUTPUT
           echo show-apps="npx nx show projects --json --type app --affected --base ${{ needs.prepare.outputs.release-tag }}" >> $GITHUB_OUTPUT
          else
           echo "No last release tag exists, all apps will be deployed"
           echo exec-cmd="npx nx run-many" >> $GITHUB_OUTPUT
           echo show-apps="npx nx show projects --json --type app" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install environment
        run: yarn install

      - name: Run lint
        run: ${{ steps.nx.outputs.exec-cmd }} -t lint

      - name: Pull postgres image, before running tests
        run: docker pull postgres:15.4-alpine

      - name: Verify changed apps and libraries are buildable
        run: ${{ steps.nx.outputs.exec-cmd }} -t build

      - name: Tests coverage
        run: ${{ steps.nx.outputs.exec-cmd }} -t test --codeCoverage

      - name: Get affected projects
        id: get-affected-projects
        run: echo affected-projects=$(${{ steps.nx.outputs.show-apps }} --with-target build) >> $GITHUB_OUTPUT

  init-state-app:
    needs: [ lint-and-run-tests, prepare ]
    strategy:
      matrix:
        environment: ${{ fromJson(needs.prepare.outputs.environments) }}
        project: ${{ fromJson(needs.lint-and-run-tests.outputs.affected-projects) }}
    uses: softkitit/github-actions-terraform/.github/workflows/controller-initialize-terraform-state.yml@main
    with:
      organization: ${{ github.event.repository.owner.login }}
      repository-name: ${{ github.event.repository.name }}
      project-name: ${{ matrix.project }}
      environment: ${{ matrix.environment }}
      terraform-folder: apps/${{ matrix.project }}/terraform
    secrets: inherit

  init-state-ci:
    if: ${{ !needs.prepare.outputs.is-release }}
    needs: [lint-and-run-tests, init-state-app]
    strategy:
      matrix:
        environment: ["deployment"]
        project: ${{ fromJson(needs.lint-and-run-tests.outputs.affected-projects) }}
    uses: softkitit/github-actions-terraform/.github/workflows/controller-initialize-terraform-state.yml@main
    with:
      organization: ${{ github.event.repository.owner.login }}
      repository-name: ${{ github.event.repository.name }}
      project-name: ${{ matrix.project }}
      environment: ${{ matrix.environment }}
      terraform-folder: apps/${{ matrix.project }}/terraform-ci
    secrets: inherit

  plan-app:
    needs: [lint-and-run-tests, init-state-app, prepare]
    strategy:
      matrix:
        environment: ${{ fromJson(needs.prepare.outputs.environments) }}
        project: ${{ fromJson(needs.lint-and-run-tests.outputs.affected-projects) }}
    uses: softkitit/github-actions-terraform/.github/workflows/ci-terraform-plan-and-format.yml@main
    with:
      environment: ${{ matrix.environment }}
      terraform-folder: apps/${{ matrix.project }}/terraform
      override-plan-comment: false
    secrets: inherit

  plan-ci:
    needs: [lint-and-run-tests, init-state-ci]
    if: ${{ !needs.prepare.outputs.is-release }}
    strategy:
      matrix:
        environment: ["deployment"]
        project: ${{ fromJson(needs.lint-and-run-tests.outputs.affected-projects) }}
    uses: softkitit/github-actions-terraform/.github/workflows/ci-terraform-plan-and-format.yml@main
    with:
      environment: ${{ matrix.environment }}
      terraform-folder: apps/${{ matrix.project }}/terraform-ci
      override-plan-comment: false
    secrets: inherit

